//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_2.my_ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int ID_Session { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public Nullable<System.DateTime> Time_Start { get; set; }
        public Nullable<int> ID_Fine { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Fine Fine { get; set; }
    }
}
